name: Sync main to public

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # necesario para forzar pushes

      - name: Push to public repo
        run: |
          git remote add public \
            https://x-access-token:${{ secrets.PUBLIC_REPO_PAT }}@github.com/antonioajlb98/PublicAndroidTPV.git
          git push public main --force
